version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - patrickhulce
  assignees:
  - patrickhulce
  labels:
  - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope